### ISSUE TITLE
eslint rules

### ISSUE THREAD

**Issue by crazko** [crazko/zoomint-web-scripts#2]
https://www.npmjs.com/package/eslint-config-react-app

**Comment by crazko** [comment]
sort absolute / relative imports

**Comment by zoltan-kovac** [comment]
Do we want to use any of these plugins? https://www.npmjs.com/search?q=eslint-plugin

**Comment by crazko** [comment]
We will see. This will probably be a foundation with possible future enhancements:

- eslint-config-esnext
- https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb
- https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md
- eslint-config-prettier
-
- @typescript-eslint/parser
- @typescript-eslint/eslint-plugin

Settings for react will probably be a separated configuration
