### ISSUE TITLE
Add `.node-version` file please

### ISSUE THREAD

**Issue by crazko** [crazko/zoomint-web-scripts#4]
Add `.node-version` file please

_Originally posted by @imtoo in https://github.com/crazko/zoomint-web-scripts/pull/3#issuecomment-578760127_

**Comment by crazko** [comment]
@imtoo Can you please elaborate more? What programs use this file and how do they so? There is some discussion here https://stackoverflow.com/questions/27425852/what-uses-respects-the-node-version-file ...

There is also possibility to use [`engines` property](https://docs.npmjs.com/files/package.json#engines) in `package.json` file, which I'd prefer, but I do not understand the use case...

**Comment by imtoo** [comment]
It's used by `avn` https://github.com/wbyoung/avn and some other node version managers.

Basically, when you `cd` to some directory with `.node-version` file it automatically switches your node version to one that is written in that file. So you don't have to check `package.json` and manually switch the node version.

**Comment by crazko** [comment]
OK, so I think now there's a different usage for both options:

- `.node-version` as you said above, i.e. while development
- `engines` works when adding / installing package, i.e. while consuming the package

I'll include it in a separate PR.

**Comment by imtoo** [comment]
Good, thank you 👍
